version: "3.1"
services:
  web:
    image: golang:latest
    env_file: .env
    ports:
      - "8080:8080"
    volumes: 
      - ./app:/app
    links: 
      - mysql
    depends_on: 
      - mysql
    command: ["/app"]
  mysql:
    image: mysql:latest
    volumes: 
      - ./providers/mysql/scheme.sql:/docker-entrypoint-initdb.d/scheme.sql
    environment: 
      - MYSQL_DATABASE=database
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes